=== Sokkero/dr-json/schemas/project-file-schema.json
{
  "$id": "https://raw.githubusercontent.com/innogames/dr-json/v0.8.0/schemas/project-file-schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "Schema for dr.json project file",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "minVersion": {
      "type": "string"
    },
    "directories": {
      "type": "object",
      "properties": {
        "schemas": {
          "type": "string"
        },
        "data": {
          "type": "string"
        },
        "variantData": {
          "type": "string"
        }
      }
    },
    "variantTypes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "variantId": {
            "type": "string"
          },
          "vars": {
            "type": "object"
          }
        },
        "required": [
          "name",
          "variantId",
          "vars"
        ]
      }
    }
  },
  "required": [
    "name"
  ],
  "additionalProperties": false
}

=== Sokkero/dr-json/example/dr.json
{
  "name": "Example Project",
  "minVersion": "0.14.1",
  "directories": {
    "schemas": "schemas",
    "data": "data",
    "variantData": "variantData"
  },
  "variantTypes": [
    {
      "name": "Difficulty",
      "variantId": "difficulty_{mode}",
      "vars": {
        "mode": {
          "title": "Mode",
          "type": "string",
          "enum": [
            "easy",
            "hard"
          ]
        }
      }
    },
    {
      "name": "AB Test",
      "variantId": "ab_{testName}.{testGroup}",
      "vars": {
        "testName": {
          "title": "Test Name",
          "type": "string"
        },
        "testGroup": {
          "title": "Test Group",
          "type": "string"
        }
      }
    }
  ]
}
